/* >>>>>>>>>>>>>>> 2048 GAME <<<<<<<<<<<<<<< */

// This is the main file. Here we call the functions generated by the other documents. This is responsible for running the game.

const table = require('table');
const inputJs = require('./input');
const mapJs = require('./map');

mapJs.fillMatrix(inputJs.gameBoard);
console.log(table.table(inputJs.gameBoard));
